esphome:
  name: esp-gas
  platform: ESP32
  board: nodemcu-32s

logger:

api:

ota:

wifi:
  ap:
    ssid: "Gas_Monitor"

web_server:
  port: 80       

captive_portal:

globals:
  # 累计用气量（m³）
  - id: total_gas_usage
    type: float
    restore_value: yes
    initial_value: '0.0'

  # 每个脉冲对应体积（m³）
  - id: pulse_volume
    type: float
    restore_value: yes
    initial_value: '0.01'
    
# 脉冲状态传感器
binary_sensor:
  - platform: gpio
    name: "Gas Pulse State"
    id: gas_pulse_state
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
      allow_other_uses: true    
    filters:
      - delayed_off: 1s



# pulse_counter 采集脉冲
sensor:
  - platform: pulse_counter
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      allow_other_uses: true   
    id: gas_pulse_raw
    name: "Gas Pulse Raw"
    internal_filter: 13us
    update_interval: 60s
    accuracy_decimals: 0

    # ⚠️ 关键：用 total 累加脉冲
    total:
      id: gas_pulse_total
      internal: true   # HA中不显示此实体
      accuracy_decimals: 0

      on_value:
        then:
          - lambda: |-
              static uint32_t last_total = 0;
              uint32_t delta = (uint32_t)x - last_total;

              // 软件层防抖：一次结算多次脉冲
              if (delta > 0) {
                id(total_gas_usage) += delta * id(pulse_volume);
                id(gas_meter).publish_state(id(total_gas_usage));
                last_total = (uint32_t)x;
              }
   

  # 用气量传感器（m³）
  - platform: template
    name: "Meter"
    id: gas_meter
    unit_of_measurement: "m³"
    accuracy_decimals: 3
    device_class: gas
    state_class: total_increasing
    update_interval: 60s
    lambda: |-
      return id(total_gas_usage);

# 数值设置
number:
  # 手动校正总气量
  - platform: template
    name: "Gas Usage Correction"
    id: gas_usage_correction
    min_value: 0
    max_value: 99999
    step: 0.01
    optimistic: true
    restore_value: true
    initial_value: 0
    set_action:
      then:
        - lambda: |-
            id(total_gas_usage) = x;
            id(gas_meter).publish_state(id(total_gas_usage));
            id(gas_usage_correction).publish_state(0);

  # ⭐ 每脉冲体积可调
  - platform: template
    name: "Pulse Volume"
    id: pulse_precision
    unit_of_measurement: "m³"
    min_value: 0.0001
    max_value: 1
    step: 0.001
    optimistic: true
    restore_value: true
    initial_value: 0.01
    set_action:
      then:
        - lambda: |-
            id(pulse_volume) = x;

# 重启
button:
  - platform: restart
    name: "Restart"

# 网络信息
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    mac_address:
      name: Mac Address
